# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task: maps
      - task: build

  build:
    cmds:
      - odin run ../karl2d/build_web -- ./game -o:minimal

  run:
    dir: '{{.TASKFILE_DIR}}/game/bin/web'  
    cmds:
      - python -m http.server 8000

  maps:
    cmds:
      - tiled --export-tileset ./assets/fullsheet.tsx fullsheet.tsj --minimize
      - tiled --export-map ./assets/mine.tmx ./assets/mine.tmj --minimize
      - tiled --export-map ./assets/new_one.tmx ./assets/arena.tmj --minimize
      - tiled --export-map ./assets/cave.tmx ./assets/cave.tmj --minimize
      #- jq -c '.tilesets[].source = "fullsheet.tsj"' ./assets/mine.tmj > ./mine.tmj
